language: php

sudo: false

matrix:
    include:
        - php: hhvm
        - php: 5.5
        - php: 5.6
        - php: 7

before_script:
  - curl --version
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit -v

after_script:
  - php vendor/bin/coveralls -v
