language: php

sudo: false

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: hhvm-3.9
          dist: trusty

before_script:
  - curl --version
  - composer self-update
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit -v

after_script:
  - php vendor/bin/coveralls -v

after_success:
  - if  [ $TRAVIS_PHP_VERSION = '7.1' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh bin/generate-api; fi
